---
spring:
  application.name: apiDataservice
datasource:
  service-name: apids
  min-pool: 10
  max-pool: 20
  max-wait-time: -1
  jpa:
    hibernate.ddl-auto: update        
    show_sql: true
api.security.username: apiuser123
api.security.password: YXBpdXNlcg==
APP_NAME: apiDataservice
APM_PORT: 5443
APM_SSL_DEFAULT: com.wily.isengard.postofficehub.link.net.SSLSocketFactory